In [ ]:
from keras.models import Model
from keras.layers import Input, Dense
from keras.datasets import mnist
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf
import numpy as np
import sys
import keras.backend as K
(x_train, y_train), (x_test,y_test) = mnist.load_data()
x_train = x_train.reshape(60000,784)
#turn y_train into one hot
y_train = [[x] for x in y_train]
y_train = OneHotEncoder().fit_transform(y_train).toarray()

a = Input(shape=(784,)) # try to code an example that has place holder in it
b = Dense(32)(a)

# sess = tf.Session()
# with sess.as_default():
#     print_op = tf.print(b, output_stream=sys.stderr)
#     sess.run(print_op, feed_dict={a:x_train})
c = Dense(10)(b)
model = Model(inputs=a,outputs=c)
print(K.print_tensor(b))
model.compile(optimizer="adam", loss= "categorical_crossentropy", metrics = ["accuracy"])
model.fit(x_train, y_train, batch_size=1, epochs=1)

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`



C:\Users\Anak\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


Tensor("Print:0", shape=(?, 32), dtype=float32)
Epoch 1/1
17326/60000 [=======>......................] - ETA: 1:05 - loss: 9.4632 - acc: 0.1617

In [15]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x,x)
rand_array = np.random.rand(1024,1024)
with tf.Session() as sess:
#     print(sess.run(y))
    
    print(sess.run(y, feed_dict={x: rand_array}))

[[256.31076 263.20673 268.0352  ... 257.28516 265.69806 255.0392 ]
 [246.20952 258.62988 261.238   ... 255.17969 260.04004 252.99377]
 [251.28355 258.47815 258.6135  ... 247.69351 258.498   263.86584]
 ...
 [249.98326 255.75203 265.83215 ... 253.8299  259.98798 256.6078 ]
 [256.7756  265.07907 272.51968 ... 265.16052 267.24524 267.85205]
 [254.67815 259.3613  267.36923 ... 259.4161  263.31366 261.51508]]


In [27]:
import numpy as np
from keras import backend as K
i = K.placeholder(shape=(4,), name ="input")
o = K.placeholder(shape=(4,), name ="output")
f = K.function([i], [o])
ival = np.ones((4,))
print(f([ival]))

InvalidArgumentError: You must feed a value for placeholder tensor 'output_1' with dtype float and shape [4]
	 [[{{node output_1}}]]

In [20]:
input_ph = K.placeholder(shape=(2,4,), name = "exo")
input_1 = K.placeholder(shape=(2,4,), name = "input_1")
display(input_ph._keras_shape)
display(input_ph)
display(input_1)

(2, 4)

<tf.Tensor 'exo_1:0' shape=(2, 4) dtype=float32>

<tf.Tensor 'input_1_10:0' shape=(2, 4) dtype=float32>

In [130]:
K.print_tensor(input_ph)

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`



<tf.Tensor 'Print:0' shape=(2, 4) dtype=float32>

In [29]:
import numpy as np
from keras import backend as K
i = K.placeholder(shape=(4,), name ="input")
square = K.square(i)
f = K.function([i], [square])
ival = np.ones((4,)) * 2
print(f([ival]))

[array([9., 9., 9., 9.], dtype=float32)]


In [129]:
import numpy as np
import tensorflow as tf
from keras import backend as K

np.random.seed(1)
# val = np.random.random((4))
# i = K.variable(value = val)

i = K.placeholder(shape=(4,), name ="input")
ival = np.ones((4,)) 

square = K.square(i)
mean = K.mean(i)
identity = K.identity(i)
mean_of_square = K.mean(K.square(i))

#######3
# Convert Tensor Object to array using K.function
########3
# f = K.function([i], [ identity,square, mean , mean_of_square])
# f = K.function([i], [identity])
# print(f([ival]))

####33
## Convert Tensor Object to array by RUNING A SESSION 
####
# sess = tf.Session()
# with sess.as_default():
#     init=tf.global_variables_initializer()
#     sess.run(init)
#     display(i.eval(session=sess))
# #     display(i.eval(session= sess, feed_dict={i: ival}))
# #     display(val)
i


<tf.Tensor 'input_28:0' shape=(4,) dtype=float32>

In [13]:
from keras import backend as K 
import numpy as np
i = K.placeholder(shape =(4,), name = 'input')
square = K.square(i)
grad = K.gradients([square], [i])

f = K.function([i], [square]+grad)

#feed input
ival = np.ones((4,)) *3
print(f([ival]))

TypeError: Can not convert a list into a Tensor or Operation.

In [17]:
K.gradients??

In [16]:
K.square??

THERE ARE 2 WAYS TO BULD MODELS
1. sequential
    > 2 ways
2. functional api


In [125]:
# Sequential
from keras.models import Sequential
from keras.layers import Dense, Activation
model = Sequential([
    Dense(32, input_shape= (784,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

In [126]:
# Sequantial with .add() method
model = Sequential()
model.add(Dense(32,input_dim=784))
model.add(Activation('relu'))

In [ ]:
# Functional api
from Keras.models import Model #what is Model for?
# This returns a tensor
input = Input(shape-(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(64, activation = 'relu')(inputs)
x = Dense(64, activation = 'relu')(x)
predictions = Dense(10, activation = 'softmax')(x)

# This creates a model that includes
# the Input layer and three Dense layers
model = Model(inputs = inputs, outputs=predictions)
model.compile(optimizer='rmsprop',
             loss ='categorical_crossentropy',
             metrics=['accuracy'])
# model.fit(data,labels)




In [18]:
x = [1,2,3,4]
x[:-1]

[1, 2, 3]