Calling Kers layers on Tensorflow tensors

In [1]:
#creating a tensorflow session andregistering it with Keras. 
# > Keras will sue the session we registered to initialzie all viralbes 
#  that it creats internally .
import tensorflow as tf
sess =tf.Session()

from keras import backend as K 
K.set_session(sess)

Using TensorFlow backend.


In [2]:
img = tf.placeholder(tf.float32, shape = (None, 784))

In [3]:
from keras.layers import Dense
x = Dense(128,activation='relu')(img)
x = Dense(128,activation='relu')(x)
preds = Dense(10,activation='softmax')(x)

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
#define placeholder for the labels and the loss function we will use
labels = tf.placeholder(tf.float32, shape=(None,10))

from keras.objectives import categorical_crossentropy
loss = tf.reduce_mean(categorical_crossentropy(labels,preds))

In [34]:
from tensorflow.examples.tutorials.mnist import input_data
mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)

train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)

#initialie all variable
init_op = tf.global_variables_initializer()
sess.run(init_op)

#run trainign lopp
with sess.as_default():
    for i in range(100):
        batch = mnist_data.train.next_batch(50)
#         print(batch[0].shape) # (batch, feature)
#         print(batch[1].shape) # (batch, label)
        train_step.run(feed_dict={img:batch[0],labels:batch[1]})

Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [25]:
# evaluate the model
from keras.metrics import categorical_accuracy as accuracy

acc_value = accuracy(labels, preds)
with sess.as_default():
    print(acc_value.eval(feed_dict={img:mnist_data.test.images,
                                   labels:mnist_data.test.labels}))

[1. 1. 1. ... 1. 1. 1.]


Different behaviors during training and testing

In [30]:
# what does learning phase do?
# when learning_phase is true: testing and traing behave differntly
from keras.layers import Dropout
from keras import backend as K

img = tf.placeholder(tf.float32, shape=(None, 784))
labels = tf.placeholder(tf.float32, shape=(None, 10))

x = Dense(128, activation='relu')(img)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
preds = Dense(10, activation='softmax')(x)

loss = tf.reduce_mean(categorical_crossentropy(labels, preds))

#initialie all variable
init_op = tf.global_variables_initializer()
sess.run(init_op)

train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
with sess.as_default():
    for i in range(100):
        batch = mnist_data.train.next_batch(50)
        train_step.run(feed_dict={img: batch[0],
                                  labels: batch[1],
                                  K.learning_phase(): 1})

acc_value = accuracy(labels, preds)
with sess.as_default():
    print(acc_value.eval(feed_dict={img: mnist_data.test.images,
                                    labels: mnist_data.test.labels,
                                    K.learning_phase(): 0}))

[1. 1. 1. ... 1. 1. 1.]


In [31]:
accuracy??

Using Keras models with TensorFlow

In [38]:
from keras.models import Sequential
model = Sequential()
# This is our modified Keras model
model.add(InputLayer(input_tensor=custom_input_tensor,
                    input_shape=(None,784)))

# build the rest of the model as before
model.add(Dense(32, activation = 'relu',input_dim=784))
model.add(Dense(10,activation='softmax'))

Calling a Keras model on a TensorFlow tensor

In [44]:
columns = ['1', 'A1BG', '0.857', '0.172', 'C0019209']


In [46]:
for j,val in enumerate(columns):
    import re
    x = re.fullmatch("([A-Z][0-9]+)", val)
    print(x)

None
None
None
None
<_sre.SRE_Match object; span=(0, 8), match='C0019209'>
